services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app-stage
    volumes:
      - uploads:/app/storage/app
      - app_logs:/app/storage/logs
      - nginx_logs:/var/log/nginx
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_shop
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:8-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - net
    volumes:
      - redis_data:/data
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx-stage
    ports:
     - "8080:80"
    volumes:
    - uploads:/app/storage:ro
    - nginx_logs:/var/log/nginx
    networks:
    - net
    depends_on:
    - app
volumes:
  db_data:
  uploads:
  app_logs:
  nginx_logs:
  redis_data:
networks:
  net:
    driver: bridge
